name: Python CI with Docker and Formatting Check

on: [push, pull_request]

jobs:
  python_formatter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Black Formatter
        uses: lgeiger/black-action@master
        with:
          args: ". --check --diff"

  cpp_formatter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Clang Formatter
        uses: jidicula/clang-format-action@v4.13.0
        with:
          clang-format-version: "13"
          check-path: "."
          fallback-style: "Mozilla"

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker
        uses: docker/build-push-action@v6
        with:
          push: false
